<?php

declare(strict_types=1);

namespace skyblock\entity\projectile;

use pocketmine\block\Liquid;
use pocketmine\entity\EntitySizeInfo;
use pocketmine\event\entity\ProjectileHitEvent;
use pocketmine\math\Vector3;
use pocketmine\nbt\tag\CompoundTag;
use pocketmine\network\mcpe\protocol\types\entity\EntityIds;
use pocketmine\player\Player;
use pocketmine\utils\Random;
use pocketmine\world\particle\BubbleParticle;
use pocketmine\world\sound\BucketFillWaterSound;
use skyblock\items\sets\SpecialSetHandler;
use skyblock\items\tools\SkyBlockFishingRod;
use skyblock\Main;
use skyblock\misc\pve\fishing\HotspotHandler;
use skyblock\misc\pve\zone\FishZone;
use skyblock\misc\pve\zone\ZoneHandler;
use skyblock\utils\Utils;

class FishingRodEntity extends SkyBlockProjectile {


	/** @var float */
	public $height = 0.25;
	/** @var float */
	public $width = 0.25;

	/** @var float */
	protected $gravity = 0.1;



	private int $maxFishTime = 300 * 20;
	private int $fishTime = 0;
	private bool $active = false;
	private int $time = 0;
	private int $range = 12;

	private bool $checked = false;

	public function isFireProof(): bool
	{
		return true;
	}

	protected function initEntity(CompoundTag $nbt): void
	{
		parent::initEntity($nbt);
		$this->setHealth(100);

		$this->range = 30;
		$this->setCanSaveWithChunk(false);
	}

	protected function onHit(ProjectileHitEvent $event) : void{
		parent::onHit($event); // TODO: Change the autogenerated stub

		$this->flagForDespawn();;
	}

	public function handleHookCasting(Vector3 $motion, float $f1, float $f2): void
	{
		$x = $motion->getX();
		$y = $motion->getY();
		$z = $motion->getZ();

		$rand = new Random();
		$f = sqrt($x * $x + $y * $y + $z * $z);
		$x /= $f;
		$y /= $f;
		$z /= $f;
		$x += $rand->nextSignedFloat() * 0.007499999832361937 * $f2;
		$y += $rand->nextSignedFloat() * 0.007499999832361937 * $f2;
		$z += $rand->nextSignedFloat() * 0.007499999832361937 * $f2;
		$x *= $f1;
		$y *= $f1;
		$z *= $f1;
		$this->motion->x += $x;
		$this->motion->y += $y;
		$this->motion->z += $z;
	}

	public function getResultDamage(): int
	{
		return 1;
	}


	/**
	 * @param float|int $maxFishTime
	 */
	public function setMaxFishTime(float|int $maxFishTime) : void{
		$this->maxFishTime = $maxFishTime;
	}

	public function onUpdate(int $currentTick): bool
	{
		if($this->isClosed() || $this->isFlaggedForDespawn()){
			return false;
		}

		$owner = $this->getOwningEntity();
		if ($owner instanceof Player) {
			if (!$owner->isAlive() || $owner->isClosed() || !$owner->getInventory()->getItemInHand() instanceof SkyBlockFishingRod) {
				$this->flagForDespawn();
			}

			if($this->isOnFire() && strtolower($this->getWorld()->getDisplayName()) !== "nether"){
				$this->flagForDespawn();
				$owner->sendMessage(Main::PREFIX . "You cannot fish in lava");
			}


			$underwater = $this->isUnderwater();

			if($this->active === true){
				if(++$this->time >= 25){
					$this->active = false;
					$this->time = 0;
					$this->fishTime = 0;
				}

				if($this->time % 5 === 0) {
					$owner->getWorld()->addSound($this->getLocation(), new BucketFillWaterSound(), [$owner]);
				}
				$this->getWorld()->addParticle($this->getLocation(), new BubbleParticle());
			}

			if($this->getLocation()->distance($owner->getLocation()) >= $this->range){
				$this->flagForDespawn();
			}

			if ($underwater === true) {
				$this->location->y += 0.3;
			}

			if($this->inWater()){
				$this->fishTime += 3;
				if($this->fishTime >= $this->maxFishTime){
					$this->fishTime = 0;
					$this->time = 0;
					$this->active = true;
					//$owner->sendTip("§b§lCatch!");
					$this->location->y -= 0.85;

					$owner->getWorld()->addSound($this->getLocation(), new BucketFillWaterSound(), [$owner]);

				} elseif(!$this->active) {
					//$owner->sendTip("§b" . $this->getSecondsLeft());

					if(!$this->checked){
						$this->checked = true;
						if(HotspotHandler::isInitialized() && HotspotHandler::getInstance()->isInsideHotspot($this->getPosition())){
							$this->fishTime -= HotspotHandler::getInstance()->getBoost()->fasterFishingInTicks;
						}

						$zone = ZoneHandler::getInstance()->getZoneByVector($this->getPosition());

						if($zone instanceof FishZone){
							$owner->sendActionBarMessage(Utils::getRandomColor() . "Fishing in " . $zone->getName());
						}
					}
				}
			}
		}
		else {
			$this->flagForDespawn();
		}


		return parent::onUpdate($currentTick);
	}

	public function getSecondsLeft(): float {
		$ticksLeft = $this->maxFishTime - $this->fishTime;

		return round($ticksLeft / 20, 1);
	}

	public function inWater(): bool {
		return $this->getWorld()->getBlock($this->getLocation()) instanceof Liquid;
	}


	/**
	 * @param bool $active
	 */
	public function setActive(bool $active): void
	{
		$this->active = $active;
		$this->time = 0;
		$this->fishTime = 0;
	}


	public function isActive(): bool
	{
		return $this->active;
	}

	protected function getInitialSizeInfo() : EntitySizeInfo{
		return new EntitySizeInfo(0.25, 0.25);
	}

	public static function getNetworkTypeId() : string{
		return EntityIds::FISHING_HOOK;
	}
}