---
libasynql:
  # The database type. "sqlite" and "mysql" are supported.
  type: mysql

  # Edit these settings only if you choose "sqlite".
  sqlite:
    # The file name of the database in the plugin data folder.
    # You can also put an absolute path here.
    file: data.sqlite
  # Edit these settings only if you choose "mysql".
  mysql:
    host: 127.0.0.1
    # Avoid using the "root" user for security reasons.
    username: ""
    password: ""
    schema: test
  # The maximum number of simultaneous SQL queries
  # Recommended: 1 for sqlite, 2 for MySQL. You may want to further increase this value if your MySQL connection is very slow.
  worker-limit: 2

logs:
  # The database type. "sqlite" and "mysql" are supported.
  type: mysql

  # Edit these settings only if you choose "sqlite".
  sqlite:
    # The file name of the database in the plugin data folder.
    # You can also put an absolute path here.
    file: data.sqlite
  # Edit these settings only if you choose "mysql".
  mysql:
    host: aetherpe.net
    # Avoid using the "root" user for security reasons.
    username: "u1_QPV8VAR8Dx"
    password: "Z3hwSd5gjB=C^f4=YDFaJvAI"
    schema: s1_logs
  # The maximum number of simultaneous SQL queries
  # Recommended: 1 for sqlite, 2 for MySQL. You may want to further increase this value if your MySQL connection is very slow.
  worker-limit: 2

...